import Todo from './Todo'
import Todolist from './TodoList'
import Exception from './Exception'
import Images from './Images'
import Files from './Files'
import Chat from './Chat'
import Login from './Login'
import Register from './Register'
import SysManage from './SysManage'
import DataTransform from './DataTransform'
import SolrFile from './SolrFile'
export default {Todolist,Exception,Images,Files,Todo,Chat,Login,Register,SysManage,DataTransform,SolrFile}
